#ifndef COMMON_H
#define COMMON_H

// The number of characters.
#define NB_SYMBOLS 256

// The maximal number of trees generated by the Huffman algorithm.
#define NB_TREES (2 * 256 + 1)

// Display an error message and quit.
void fail(const char message[]);

#endif